// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	repo "github.com/harsh-jagtap-josh/RozgarLink/internal/repo"
	mock "github.com/stretchr/testify/mock"
)

// AuthStorer is an autogenerated mock type for the AuthStorer type
type AuthStorer struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, loginData
func (_m *AuthStorer) Login(ctx context.Context, loginData repo.LoginRequest) (repo.LoginUserData, error) {
	ret := _m.Called(ctx, loginData)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 repo.LoginUserData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.LoginRequest) (repo.LoginUserData, error)); ok {
		return rf(ctx, loginData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.LoginRequest) repo.LoginUserData); ok {
		r0 = rf(ctx, loginData)
	} else {
		r0 = ret.Get(0).(repo.LoginUserData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.LoginRequest) error); ok {
		r1 = rf(ctx, loginData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthStorer creates a new instance of AuthStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthStorer {
	mock := &AuthStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
