// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/harsh-jagtap-josh/RozgarLink/internal/app/auth"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, loginData
func (_m *Service) Login(ctx context.Context, loginData auth.LoginRequest) (auth.LoginResponse, error) {
	ret := _m.Called(ctx, loginData)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 auth.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginRequest) (auth.LoginResponse, error)); ok {
		return rf(ctx, loginData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginRequest) auth.LoginResponse); ok {
		r0 = rf(ctx, loginData)
	} else {
		r0 = ret.Get(0).(auth.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.LoginRequest) error); ok {
		r1 = rf(ctx, loginData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
